language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
  - composer selfupdate
install:
  - composer update
script:
  - php ./vendor/bin/phpunit -c tests/phpunit.xml tests/
  - php ./vendor/bin/phpmetrics src/ --report-html=build/phpmetrics.html
after_success:
  - php ./build/upload-artifacts.php $WEBDAV_CREDENTIALS $TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT $TRAVIS_PULL_REQUEST $TRAVIS_BRANCH